[package]
name = "dart-semver"
description = "Rust crate for parsing dart sdk's semver"
version = "0.1.0"
authors = ["Yakiyo <yakiyo1206@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.6.0"
pest_derive = "2.6.0"
